"""
This type stub file was generated by pyright.
"""

import hashlib
import dns.enum

"""Common zone-related types."""
class DigestScheme(dns.enum.IntEnum):
    """ZONEMD Scheme"""
    SIMPLE = ...


class DigestHashAlgorithm(dns.enum.IntEnum):
    """ZONEMD Hash Algorithm"""
    SHA384 = ...
    SHA512 = ...


_digest_hashers = ...
