"""
This type stub file was generated by pyright.
"""

import collections
import random
import struct
import dns.exception
import dns.ipv4
import dns.ipv6
import dns.name
import dns.rdata
from typing import Any, List

class Gateway:
    """A helper class for the IPSECKEY gateway and AMTRELAY relay fields"""
    name = ...
    def __init__(self, type, gateway=...) -> None:
        ...
    
    def to_text(self, origin=..., relativize=...): # -> str | None:
        ...
    
    @classmethod
    def from_text(cls, gateway_type, tok, origin=..., relativize=..., relativize_to=...): # -> Self:
        ...
    
    def to_wire(self, file, compress=..., origin=..., canonicalize=...): # -> None:
        ...
    
    @classmethod
    def from_wire_parser(cls, gateway_type, parser, origin=...): # -> Self:
        ...
    


class Bitmap:
    """A helper class for the NSEC/NSEC3/CSYNC type bitmaps"""
    type_name = ...
    def __init__(self, windows=...) -> None:
        ...
    
    def to_text(self) -> str:
        ...
    
    @classmethod
    def from_text(cls, tok: dns.tokenizer.Tokenizer) -> Bitmap:
        ...
    
    @classmethod
    def from_rdtypes(cls, rdtypes: List[dns.rdatatype.RdataType]) -> Bitmap:
        ...
    
    def to_wire(self, file: Any) -> None:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser: dns.wire.Parser) -> Bitmap:
        ...
    


def priority_processing_order(iterable): # -> list[Any]:
    ...

_no_weight = ...
def weighted_processing_order(iterable): # -> list[Any]:
    ...

def parse_formatted_hex(formatted, num_chunks, chunk_size, separator): # -> bytes:
    ...

