"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Mapping, MutableMapping
from typing import Any, Optional, TYPE_CHECKING, Union
from pymongo import common
from pymongo.collation import validate_collation_or_none
from pymongo.errors import ConfigurationError
from pymongo.read_preferences import ReadPreference, _AggWritePref, _ServerMode
from pymongo.asynchronous.client_session import AsyncClientSession
from pymongo.asynchronous.collection import AsyncCollection
from pymongo.asynchronous.command_cursor import AsyncCommandCursor
from pymongo.asynchronous.database import AsyncDatabase
from pymongo.asynchronous.pool import AsyncConnection
from pymongo.asynchronous.server import Server
from pymongo.typings import _DocumentType, _Pipeline

"""Perform aggregation operations on a collection or database."""
if TYPE_CHECKING:
    ...
_IS_SYNC = ...
class _AggregationCommand:
    """The internal abstract base class for aggregation cursors.

    Should not be called directly by application developers. Use
    :meth:`pymongo.asynchronous.collection.AsyncCollection.aggregate`, or
    :meth:`pymongo.asynchronous.database.AsyncDatabase.aggregate` instead.
    """
    def __init__(self, target: Union[AsyncDatabase, AsyncCollection], cursor_class: type[AsyncCommandCursor], pipeline: _Pipeline, options: MutableMapping[str, Any], explicit_session: bool, let: Optional[Mapping[str, Any]] = ..., user_fields: Optional[MutableMapping[str, Any]] = ..., result_processor: Optional[Callable[[Mapping[str, Any], AsyncConnection], None]] = ..., comment: Any = ...) -> None:
        ...
    
    def get_read_preference(self, session: Optional[AsyncClientSession]) -> Union[_AggWritePref, _ServerMode]:
        ...
    
    async def get_cursor(self, session: Optional[AsyncClientSession], server: Server, conn: AsyncConnection, read_preference: _ServerMode) -> AsyncCommandCursor[_DocumentType]:
        ...
    


class _CollectionAggregationCommand(_AggregationCommand):
    _target: AsyncCollection
    ...


class _CollectionRawAggregationCommand(_CollectionAggregationCommand):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


class _DatabaseAggregationCommand(_AggregationCommand):
    _target: AsyncDatabase
    ...


