"""
This type stub file was generated by pyright.
"""

import sys
import types
import typing
from collections import deque
from dataclasses import is_dataclass
from typing import Any, Deque, FrozenSet, List, Mapping, Sequence, Set, Tuple, Type, Union
from fastapi._compat import may_v1
from fastapi.types import UnionType
from pydantic import BaseModel
from pydantic.version import VERSION as PYDANTIC_VERSION
from starlette.datastructures import UploadFile
from typing_extensions import Annotated, get_args, get_origin

if sys.version_info < (3, 9):
    ...
else:
    WithArgsTypes: tuple[Any, ...] = ...
PYDANTIC_VERSION_MINOR_TUPLE = ...
PYDANTIC_V2 = ...
sequence_annotation_to_type = ...
sequence_types = ...
Url: Type[Any]
def lenient_issubclass(cls: Any, class_or_tuple: Union[Type[Any], Tuple[Type[Any], ...], None]) -> bool:
    ...

def field_annotation_is_sequence(annotation: Union[Type[Any], None]) -> bool:
    ...

def value_is_sequence(value: Any) -> bool:
    ...

def field_annotation_is_complex(annotation: Union[Type[Any], None]) -> bool:
    ...

def field_annotation_is_scalar(annotation: Any) -> bool:
    ...

def field_annotation_is_scalar_sequence(annotation: Union[Type[Any], None]) -> bool:
    ...

def is_bytes_or_nonable_bytes_annotation(annotation: Any) -> bool:
    ...

def is_uploadfile_or_nonable_uploadfile_annotation(annotation: Any) -> bool:
    ...

def is_bytes_sequence_annotation(annotation: Any) -> bool:
    ...

def is_uploadfile_sequence_annotation(annotation: Any) -> bool:
    ...

def annotation_is_pydantic_v1(annotation: Any) -> bool:
    ...

