"""
This type stub file was generated by pyright.
"""

import ipaddress
import random
from typing import Any, Optional, TYPE_CHECKING, Union
from pymongo.common import CONNECT_TIMEOUT
from pymongo.errors import ConfigurationError
from dns import resolver

"""Support for resolving hosts and options from mongodb+srv:// URIs."""
if TYPE_CHECKING:
    ...
_IS_SYNC = ...
def maybe_decode(text: Union[str, bytes]) -> str:
    ...

_INVALID_HOST_MSG = ...
class _SrvResolver:
    def __init__(self, fqdn: str, connect_timeout: Optional[float], srv_service_name: str, srv_max_hosts: int = ...) -> None:
        ...
    
    def get_options(self) -> Optional[str]:
        ...
    
    def get_hosts(self) -> list[tuple[str, Any]]:
        ...
    
    def get_hosts_and_min_ttl(self) -> tuple[list[tuple[str, Any]], int]:
        ...
    


